from configs.default import _CN as cfg

cfg.LOFTR.BACKBONE_TYPE = 'Twins'
cfg.LOFTR.RESOLUTION = (8, 4, 2)

cfg.LOFTR.RESNETFPN.INITIAL_DIM = 64
cfg.LOFTR.RESNETFPN.BLOCK_DIMS = [64, 128, 256]
cfg.LOFTR.RESNETFPN.MODEL_TYPE = 'large'
cfg.LOFTR.RESNETFPN.VIT_PATH = 'pretrained_weights/alt_gvt_large.pth'

cfg.LOFTR.COARSE.D_MODEL = 256
cfg.LOFTR.COARSE.BLOCK_TYPE = "quadtree"
cfg.LOFTR.COARSE.ATTN_TYPE = "B"
cfg.LOFTR.COARSE.TOPKS = [32, 16, 8]
cfg.LOFTR.COARSE.LAYER_NAMES = ['self', 'cross', 'self', 'cross', 'self', 'cross']
cfg.LOFTR.COARSE.RELATIVE_PE = False

cfg.LOFTR.COARSE2.D_MODEL = 128
cfg.LOFTR.COARSE2.NHEAD = 4
cfg.LOFTR.COARSE2.LAYER_NAMES = ['cross', 'self', 'cross', 'self']  # local-global:27-23G? local:19G
cfg.LOFTR.COARSE2.SELF_ATTN_TYPE = 'local'  # local_global, local, VAN, topk
cfg.LOFTR.COARSE2.WINDOW_SIZE = 5
cfg.LOFTR.COARSE2.ATTN_WINDOW_SIZE = 7
cfg.LOFTR.COARSE2.PROPAGATION = 'window'  # 'dilated'
cfg.LOFTR.COARSE2.SR_RATIO = 4
cfg.LOFTR.COARSE2.DILATED = 1
cfg.LOFTR.COARSE2.RELATIVE_PE = False
cfg.LOFTR.COARSE2.TOPKS = [16, 8]
cfg.LOFTR.COARSE2.DETECTOR = None  # conf/learnable/None
cfg.LOFTR.COARSE2.DETECTOR_MODE = None  # hard gumbel or ST or None
cfg.LOFTR.COARSE2.GRID_SIZE = 4

cfg.LOFTR.COARSE2.POST_CONFIG.METHOD = 'maxpool_nms'# 'maxpool_nms'
cfg.LOFTR.COARSE2.POST_CONFIG.WINDOW_SIZE = 5
cfg.LOFTR.COARSE2.POST_CONFIG.TOPK = None

cfg.LOFTR.FINE.D_MODEL = 64
cfg.LOFTR.FINE.D_FFN = 64
cfg.LOFTR.FINE.NHEAD = 2
cfg.LOFTR.FINE.LAYER_NAMES = ['self', 'cross']
cfg.LOFTR.FINE.ATTENTION = 'vanilla'

cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = "dual_softmax"
cfg.LOFTR.MATCH_COARSE.SPARSE_SPVS = False
cfg.LOFTR.MATCH_COARSE.THR = 0.2
cfg.LOFTR.MATCH_COARSE.BORDER_RM = 0
cfg.LOFTR.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.3
cfg.LOFTR.MATCH_COARSE.NEXT_TOPK = None  # real topk: 32*4=128

cfg.LOFTR.MATCH_CASCADE.THR = [0.0101]
cfg.LOFTR.MATCH_CASCADE.PRE_THR = [[0.2]]
cfg.LOFTR.MATCH_CASCADE.TEST_THR = [0.2]
cfg.LOFTR.MATCH_CASCADE.BORDER_RM = [2]
cfg.LOFTR.MATCH_CASCADE.DOUBLE_CHECK = [True]
cfg.LOFTR.MATCH_CASCADE.MATCH_TYPE = ['softmax']
cfg.LOFTR.MATCH_CASCADE.DSMAX_TEMPERATURE = [1.0]
cfg.LOFTR.MATCH_CASCADE.TRAIN_PAD_NUM_GT_MIN = [4096]  # should consider to batch size

cfg.LOFTR.LOSS.COARSE_WEIGHT = 1.0
cfg.LOFTR.LOSS.CASCADE_WEIGHT = 1.0
cfg.LOFTR.LOSS.CASCADE_TYPE = 'focal'
cfg.LOFTR.LOSS.FINE_WEIGHT = 1.0
cfg.LOFTR.LOSS.DETECTOR_WEIGHT = 2.0

cfg.LOFTR.CASCADE = True
cfg.LOFTR.COARSE_LEVEL = 8
cfg.LOFTR.FINE_LEVEL = 2
cfg.LOFTR.CASCADE_LEVELS = [4]
cfg.LOFTR.IS_RGB = True
cfg.LOFTR.TRAIN_SIZE = 704

cfg.TRAINER.CANONICAL_LR = 8e-3
cfg.TRAINER.WARMUP_STEP = 1875  # 3 epochs
cfg.TRAINER.WARMUP_RATIO = 0.1
cfg.TRAINER.MSLR_MILESTONES = [8, 12, 16, 20, 24]

cfg.TRAINER.RANSAC_PIXEL_THR = 0.5

cfg.TRAINER.OPTIMIZER = "adamw"
cfg.TRAINER.ADAMW_DECAY = 0.01
